---
- hosts: pc
  roles:
    - common
    - i3
    - firefox
    - atom
    - networkmanager
    - mysqlworkbench
    - insomnia
    - phpstorm
    - docker
    - rambox
    - nextcloud
    - keepassx
