- name: Add the user '{{ foruser }}'
  user:
    name: "{{ foruser }}"
    comment: Working User
    generate_ssh_key: yes
    shell: /bin/zsh

- name: install zsh
  package:
    name: zsh
    state: presend
