- name: install xorg-server
  package:
    name: xorg-server
    state: present
- name: install xorg-xinit
  package:
    name: xorg-xinit
    state: present
- name: install i3-wm
  package:
    name: i3-wm
    state: present
- name: Add .xinitrc file
  template:
    src: templates/xinitrc.j2
    dest: "/home/{{ foruser }}/.xinitrc"
    mode: 0644
  become: yes
- name: install ttf-dejavu, used for default i3 config
  package:
    name: ttf-dejavu
    state: present
- name: Add i3 config file
  template:
    src: templates/i3config.j2
    dest: "/home/{{ foruser }}/.config/i3/config"
    mode: 0644
  become: yes

- name: Install font-awsome
  aur:
    name: otf-font-awesome-5-free
  become: yes
  become_user: "aur_builder"

- name: install rxvt-unicode
  package:
    name: rxvt-unicode
    state: present
- name: config rxvt-unicode with Xdefaults
  template:
    src: templates/Xdefaults.j2
    dest: "/home/{{ foruser }}/.Xdefaults"
    mode: 0644
  become: yes
