- name: install xorg-xinit
  package:
    name: xorg-xinit
    state: present
- name: install i3-wm
  package:
    name: i3-wm
    state: present
- name: Add .xinitrc file
  template:
    src: templates/xinitrc.j2
    dest: "/home/{{ foruser }}/.xinitrc"
    mode: 0644
  become: yes
