- name: install xorg-xinit
  package:
    name: xorg-xinit
    state: present
- name: install i3-wm
  package:
    name: i3-wm
    state: present
- name: Add .xinitrc file
  template:
    src: templates/mosquito_config.j2
    dest: /etc/mosquitto/conf.d/default.conf
    mode: 0644
  become: yes
