- name: install xorg-server
  package:
    name: xorg-server
    state: present
- name: install xorg-xinit
  package:
    name: xorg-xinit
    state: present
- name: install i3-wm
  package:
    name: i3-wm
    state: present
- name: Add .xinitrc file
  template:
    src: templates/xinitrc.j2
    dest: "/home/{{ foruser }}/.xinitrc"
    mode: 0644
  become: yes
- name: install ttf-dejavu, used for default i3 config
  package:
    name: ttf-dejavu
    state: present
- name: Add i3 config file
  template:
    src: templates/i3config.j2
    dest: "/home/{{ foruser }}/.config/i3/config"
    mode: 0644
  become: yes

- name: Install font-awsome
  aur:
    name: otf-font-awesome-5-free
  become: yes
  become_user: "aur_builder"

- name: install rxvt-unicode
  package:
    name: rxvt-unicode
    state: present
- name: config rxvt-unicode with Xdefaults
  template:
    src: templates/Xdefaults.j2
    dest: "/home/{{ foruser }}/.Xdefaults"
    mode: 0644

- name: install i3blocks
  package:
    name: i3blocks
    state: present

- file:
    path: "/home/{{ foruser }}/.config/i3blocks"
    state: directory
    owner: "{{ foruser }}"
    group: "{{ foruser }}"
    mode: 0755
- name: config i3 blocks config up
  template:
    src: templates/i3blocks-up.j2
    dest: "/home/{{ foruser }}/.config/i3blocks/config"
    mode: 0644
    owner: "{{ foruser }}"
    group: "{{ foruser }}"

- name: config i3 blocks config up
  template:
    src: templates/i3blocks-down.j2
    dest: "/home/{{ foruser }}/.config/i3blocks/config-down"
    mode: 0644
    owner: "{{ foruser }}"
    group: "{{ foruser }}"

- git:
    repo: 'https://github.com/vivien/i3blocks-contrib.git'
    dest: /opt/i3blocks-contrib

- name: install pacman-contrib for i3bar
  package:
    name: pacman-contrib
    state: present

- name: install acpi for i3bar
  package:
    name: acpi
    state: present

# Install rofi as demnu ersatz
- name: install rofi for rofi as demnu ersatzt
  package:
    name: rofi
    state: present

- name: install compton for rofi transparent and screen switch animation
  package:
    name: compton
    state: present


- name: config Xresources
  template:
    src: templates/xresources.j2
    dest: "/home/{{ foruser }}/.Xresources"
    mode: 0644
    owner: "{{ foruser }}"
    group: "{{ foruser }}"

- name: Background Image
  get_url:
    url: http://waldfee.me/wp-content/uploads/2019/02/DSC0491-Kopie-768x510.jpg
    dest: "/home/{{ foruser }}/.bg.jpg"
    owner: "{{ foruser }}"
    group: "{{ foruser }}"
    mode: 0644
