- name: install htop
  package:
    name: htop
    state: present

- name: install vim
  package:
    name: vim
    state: present

- name: install zsh
  package:
    name: zsh
    state: present

- name: install zsh-completions
  package:
    name: zsh-completions
    state: present

- name: Install grml zsh config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: "/home/{{ foruser }}/.zshrc"
    owner: "{{ foruser }}"
    group: "{{ foruser }}"
    mode: 0644

- name: Install grml zsh config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: "/root/.zshrc"
    mode: 0644

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  user:
    name: root
    shell: /bin/zsh

- name: Add the user '{{ foruser }}'
  user:
    name: "{{ foruser }}"
    comment: Working User
    generate_ssh_key: yes
    shell: /bin/zsh

- name: install sudo
  package:
    name: sudo
    state: present

- name: Add sudoers  file
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers
  become: yes

- user:
    name: aur_builder
    group: wheel

- name: install dnsutils
  package:
    name: dnsutils
    state: present

- file:
    path: "/home/{{ foruser }}/scripts"
    state: directory
    mode: 0755

- name: install maim
  package:
    name: maim
    state: present

- name: Install screenshot tool
  template:
    src: templates/maim.j2
    dest: "/home/{{ foruser }}/scripts/screenshot"
    mode: 0777

- name: install unp
  package:
    name: unp
    state: present

- name: install unzip
  package:
    name: unzip
    state: present
